import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { redirectRoutes, validSections } from './routes';

/**
 * What the sitemap tells search engines exists.
 *
 * `/sitemap.xml` is generated by `api/news-sitemap`, which had no tests at all
 * and two independent ways to advertise a page that is not there:
 *
 *   1. It carried its own hand-written copy of the nine dashboard sections. If
 *      that copy gained a section the dashboard does not render, the sitemap
 *      would advertise `/data/<section>` and `App.tsx` would fall back to
 *      `'all'` — serving the Overview under a distinct URL, which is the
 *      `/data/overview` duplicate-content trap aimed at Google instead of at
 *      the overflow sweep.
 *
 *   2. It listed `/correspondents/<id>`, which `main.tsx` routes to
 *      `LegacyCorrespondentRedirect`, and the page that redirect lands on sets
 *      `canonicalPath: /newsroom/<id>`. The sitemap said "index this" and the
 *      destination said "index something else".
 *
 * Both are derived here rather than restated, so the test cannot drift into
 * agreeing with a stale copy of the thing it checks.
 */

function sitemapSource(): string {
  return readFileSync(resolve('api/news-sitemap/index.js'), 'utf8');
}

/** The section ids the sitemap will advertise under `/data/`. */
function sitemapSections(): string[] {
  const block = sitemapSource().match(/const SECTIONS\s*=\s*\[([\s\S]*?)\];/);
  if (!block) throw new Error('SECTIONS not found in api/news-sitemap — the derivation is broken');

  const found = [...block[1].matchAll(/'([^']+)'/g)].map((m) => m[1]);
  if (found.length === 0) throw new Error('SECTIONS parsed to an empty list — the derivation is broken');
  return found;
}

/** Every literal path the sitemap adds, as written in the `add(...)` calls. */
function sitemapPathPrefixes(): string[] {
  return [...sitemapSource().matchAll(/add\(\s*'([^']+)'/g)].map((m) => m[1]);
}

describe('the sitemap advertises pages that exist', () => {
  it('parses, and is not silently empty', () => {
    // Without this, every assertion below passes vacuously the moment the
    // regex stops matching — which is how a derivation quietly stops checking
    // anything while staying green.
    expect(sitemapSections().length, 'no sections parsed from the sitemap').toBeGreaterThan(6);
    expect(sitemapPathPrefixes().length, 'no add() paths parsed from the sitemap').toBeGreaterThan(3);
  });

  it('advertises exactly the sections the dashboard renders', () => {
    // Set equality in both directions: a section the sitemap omits is a page
    // Google never learns about, and one it invents is a duplicate of the
    // Overview under its own URL.
    expect([...sitemapSections()].sort()).toEqual([...validSections()].sort());
  });

  it('lists no route the router only redirects away from', () => {
    const redirects = redirectRoutes();
    expect(redirects, 'the legacy correspondent route should still exist to be excluded')
      .toContain('/correspondents/:id');

    // A parameterised redirect is only excludable by prefix when it has a
    // literal segment in front of the parameter. `/:section` does not: its
    // prefix is `/`, which is the home page — an earlier, non-redirect route
    // that `/:section` never sees, because React Router matches the more
    // specific entry first. Treating `/` as a redirect prefix reported the
    // front page as an advertised redirect, which is how this assertion first
    // failed.
    const exact = new Set(redirects);
    const prefixes = redirects
      .filter((route) => /^\/[^:/]+\/:[^/]+$/.test(route))
      .map((route) => route.replace(/:[^/]+$/, ''));

    expect(prefixes, 'no excludable redirect prefixes derived').toContain('/correspondents/');

    for (const path of sitemapPathPrefixes()) {
      expect(
        exact.has(path) || prefixes.some((prefix) => path === prefix),
        `the sitemap advertises ${path}, which the router only redirects away from`,
      ).toBe(false);
    }
  });
});
