/**
 * GET /api/sea-state
 *
 * Live marine and surface weather for Latvia's three ports, in one cached
 * response.
 *
 * WHY THIS ENDPOINT EXISTS
 * ------------------------
 * The dashboard used to call Open-Meteo directly from the browser: two requests
 * per port across three ports, so **six cross-origin calls on every single load
 * of `/data`**. Those were the only upstream calls on the site that never
 * touched our cache, because they never touched our backend.
 *
 * The three ports are fixed coordinates. Every visitor was therefore fetching
 * exactly the same six payloads, independently, for data Open-Meteo republishes
 * hourly. Ten readers in a minute meant sixty requests for six distinct
 * answers, and that number rises with the audience for no gain whatsoever.
 *
 * Through here it is six upstream calls per TTL — twenty-four an hour, whether
 * one person is reading or ten thousand — and one request from the browser
 * instead of six.
 *
 * WHY THIS DOES NOT REPEAT THE OPEN-METEO THROTTLE
 * -----------------------------------------------
 * `api/shared/cache.js` records that this project has already been throttled by
 * Open-Meteo on the Static Web App's shared egress address, so moving browser
 * traffic onto that address deserves an argument rather than a shrug: the
 * browser calls came from each reader's own address, which spread the load, and
 * this concentrates it onto one.
 *
 * It is still the right move, because concentration and volume are different
 * things. What earned the throttle was asking an hourly source several times a
 * minute. Caching caps the total at twenty-four an hour however many readers
 * arrive — fewer than a single browser session already generated by opening the
 * dashboard four times. The failure that remains is handled as the rest of the
 * site handles it: the last good answer stands for its grace, carrying its age,
 * and absence is reported as `null` rather than as a calm sea.
 */

const es = require('../shared/eurostat.js');
const { withSecurity } = require('../shared/securityHeaders.js');
const { withCache } = require('../shared/responseCache.js');

const MARINE_URL = 'https://marine-api.open-meteo.com/v1/marine';
const WEATHER_URL = 'https://api.open-meteo.com/v1/forecast';

/**
 * The same three ports the dashboard draws.
 *
 * Duplicated from `src/types.ts` because the Function App is deployed from
 * `api/` alone and cannot read that file at runtime. `tests/seaState.test.ts`
 * asserts the two lists agree, so a coordinate corrected in one place cannot
 * quietly disagree with the other — which would file one port's weather under
 * another port's name.
 */
const PORTS = [
  { code: 'LVRIX', name: 'Riga', lat: 57.05, lon: 24.10 },
  { code: 'LVVNT', name: 'Ventspils', lat: 57.40, lon: 21.55 },
  { code: 'LVLPX', name: 'Liep\u0101ja', lat: 56.52, lon: 20.97 },
];

// Open-Meteo has been measured hanging for the full deadline on this egress
// address, so the budget is short and one retry is allowed: a fresh connection
// usually succeeds where waiting does not.
const DEADLINE_MS = 6000;
const RETRIES = 1;

function marineUrl(port) {
  return MARINE_URL +
    '?latitude=' + port.lat + '&longitude=' + port.lon +
    '&current=wave_height,wave_direction,wave_period,sea_surface_temperature,wind_wave_height,swell_wave_height' +
    '&hourly=wave_height,sea_surface_temperature' +
    '&forecast_days=3&timezone=Europe%2FRiga';
}

function weatherUrl(port) {
  return WEATHER_URL +
    '?latitude=' + port.lat + '&longitude=' + port.lon +
    '&current=temperature_2m,wind_speed_10m,wind_direction_10m,cloud_cover,precipitation' +
    '&timezone=Europe%2FRiga';
}

/**
 * A reading, or null.
 *
 * Never a zero. The dashboard has been burned by this exact substitution twice
 * already — a fabricated calm sea and a fabricated clean-air reading, both
 * rendered in the same colours as measurements. Zero is an ordinary wave
 * height, air temperature and wind speed on the Baltic, so a zero standing in
 * for "no answer" is indistinguishable from an observation.
 */
function num(value) {
  return typeof value === 'number' && Number.isFinite(value) ? value : null;
}

function marineOf(port, data) {
  const current = (data && data.current) || {};
  const hourly = (data && data.hourly) || {};
  return {
    portCode: port.code,
    current: {
      waveHeight: num(current.wave_height),
      waveDirection: num(current.wave_direction),
      wavePeriod: num(current.wave_period),
      seaSurfaceTemp: num(current.sea_surface_temperature),
      windWaveHeight: num(current.wind_wave_height),
      swellWaveHeight: num(current.swell_wave_height),
    },
    hourly: {
      time: Array.isArray(hourly.time) ? hourly.time : [],
      waveHeight: Array.isArray(hourly.wave_height) ? hourly.wave_height : [],
      seaSurfaceTemp: Array.isArray(hourly.sea_surface_temperature) ? hourly.sea_surface_temperature : [],
    },
  };
}

function weatherOf(port, data) {
  const current = (data && data.current) || {};
  return {
    portCode: port.code,
    temperature: num(current.temperature_2m),
    windSpeed: num(current.wind_speed_10m),
    windDirection: num(current.wind_direction_10m),
    cloudCover: num(current.cloud_cover),
    precipitation: num(current.precipitation),
  };
}

const handler = async function (context, req) {
  const settled = await Promise.allSettled(PORTS.map(async function (port) {
    // The two services fail independently and are not equally important, so
    // they are awaited independently.
    //
    // Joining them with `Promise.all` was the defect #143 fixed on the browser
    // side, and moving the fetch to the server would have reintroduced it: a
    // single 500 from the land forecast rejected the pair and dropped the whole
    // port, so a run where the marine API answered perfectly returned no ports
    // at all — every card lost, including the wave heights that had arrived.
    //
    // The sea state is the point of the card; the air temperature is context
    // beside it. So a land failure yields `weather: null` and the port stays,
    // and a marine failure drops that port and only that port. `PortCard` was
    // always written for this: it reads `weather?.temperature` through
    // `fixed()`, which renders an em dash.
    const [marine, weather] = await Promise.all([
      es.httpJson(marineUrl(port), { deadlineMs: DEADLINE_MS, retries: RETRIES }),
      es.httpJson(weatherUrl(port), { deadlineMs: DEADLINE_MS, retries: RETRIES })
        .catch(function () { return null; }),
    ]);
    return {
      port: port,
      marine: marineOf(port, marine),
      weather: weather === null ? null : weatherOf(port, weather),
    };
  }));

  const ports = settled
    .filter(function (r) { return r.status === 'fulfilled'; })
    .map(function (r) { return r.value; });

  // One port failing must not blank the other two, but all three failing is a
  // failure and has to read as one rather than as an empty, becalmed coastline.
  if (ports.length === 0) {
    context.res = {
      status: 502,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        error: 'Open-Meteo did not answer for any port',
        source: 'Open-Meteo',
      }),
    };
    return;
  }

  context.res = {
    status: 200,
    headers: { 'Content-Type': 'application/json', 'Cache-Control': 'public, max-age=900' },
    body: JSON.stringify({
      ports: ports,
      // Named, so a client can tell "Liepāja is missing" from "Liepāja is calm".
      unavailable: PORTS
        .filter(function (p) { return !ports.some(function (r) { return r.port.code === p.code; }); })
        .map(function (p) { return p.code; }),
      source: 'Open-Meteo',
      fetchedAt: new Date().toISOString(),
    }),
  };
};

module.exports = withSecurity(withCache(handler, {
  name: 'sea-state',
  keyOn: [],
  // Open-Meteo publishes hourly, so a quarter of an hour loses nothing.
  ttlMs: 15 * 60 * 1000,
  graceMs: 60 * 60 * 1000,
  staleWhileRevalidate: true,
}));
module.exports.PORTS = PORTS;
